- name: 'Money Transfer'
  tag_line: Easiest way to transfer cash to anyone
  social_image: https://ekoin.netlify.app/images/money-transfer/easy-cash-transfer.png
  keywords: money, transfer, easy
  hero_image: /images/money-transfer/money-transfer.svg
  summary: A simple and highly secure direct money transfer ability for your customers using cash with industry-leading success rates
  description: Eko’s remittance service gives you the feature to turn your own shop into a bank. Customers who do not have bank accounts but still want to transfer money using cash can visit your shop. You can take the cash and transfer digital money to the bank account specified by them. Easy and effective!

  layout:
    - section: mid_summary
      small_description: Money Transfer
      header: Instant money transfer, anytime & anywhere
    - section: alternating_steps
      steps:
      - title: Easy Cash transfer
        text: 'Customers can transfer cash to anyone by specifying their bank details right at your doorstep'
        image: /images/money-transfer/easy-cash-transfer.svg
      - title: Transaction-assurance
        text: Assure your customers that their money is safe using our transaction assurance option
        image: /images/money-transfer/transaction-assurance.svg
      - title: Transaction receipt
        text: Print transaction-receipt for your customers to give them a sense of safety
        image: /images/money-transfer/transaction-receipt.svg
      # Can add more steps here
    - section: heros_main_section
      header: Benefits
      heros: 
        - type: pair # 2 heros side-by-side
          # Benefit 1
          title_left: Earn Commission
          text_left: Earn commission for every cash-deposit, cash-withdrawal or balance-inquiry that your customer does at your shop. More transaction is more commission for you.
          image_left: /images/money-transfer/earn-commission.svg
          # Benefit 2
          title_right: Best Success Rate
          text_right: Transaction failures occur rarely with our services. We ensure that you get the best success rate for every transaction. We are as reliable as banks themselves
          image_right: /images/money-transfer/best-success-rate.svg
        - type: single # One hero on its own in the center of the page
          # Benefit 3 (center)
          title: Turn your shop into a mini bank
          text: Since money transfer is the most commonly used banking service, this feature will turn your shop into a mini bank for customers! Consequently, more customers will visit your shop
          image: /images/money-transfer/mini-bank.svg
        - type: pair
          # Benefit 4 (left side)
          title_left: Avoid Bank Queues
          text_left: Customers would no longer need to stand in queues for banking services. They can simply visit your shop and use these services.
          image_left: /images/money-transfer/avoid-bank-queues.svg
          # Benefit 5 (right side)
          title_right: Save Travel Money
          text_right: Customers can save time and money by not having to travel to bank branches. They can use all these basic banking services at your shop.
          image_right: /images/money-transfer/save-money.svg
    - section: one_liner
      icon: /images/eko-trust.svg
      title: Eko's Trust
      text: You can assure your customers that their money and data is safe. Eko’s trust is unparalleled
    - section: step_section
      header: How money transfer works
      boxes:
      - title: 'Step 1:'
        text: Sign Up on Connect
        link: https://connect.eko.in/
      - title: 'Step 2:'
        text: Enter customer mobile number
      - title: 'Step 3:'
        text: Enter amount and bank details
      - title: 'Step 4:'
        text: Click send and collect cash
    - section: message
      line1: A customer who wishes to use your service would simply need to provide his mobile number and details of the bank account to transfer money to. 
      main_line: For all issues, we provide 24x7 support.
      button_text: Contact Support
    - section: final_ad
      small_header: Ready to get started?
      main_header: Become Eko Partner & Earn More
      image: /images/become-eko-partner.svg
      button1_text: Get Started
      button2_text: Contact Sales


- name: Aadhaar Banking / Cash-out
  tag_line: AePS - Aadhaar Enabled Payment System
  social_image: https://ekoin.netlify.app/images/aadhaar-banking/AePS_hero.png
  keywords: Aadhaar Banking, Cash-out
  hero_image: /images/aadhaar-banking/AePS_hero.svg
  summary: A simple and highly secure cash withdrawing ability for your customers using Aadhaar and ensuring that you earn more with every transaction.
  description: Aadhar banking (AePS) helps you turn your own shop into an ATM. It provides you the ability to deliver services such as cash deposit, cash withdrawal, and balance check to your customers. This is particularly useful for customers who do not trust themselves to be able to use an ATM properly. Help them out, help yourself out!
  icon: /images/aadhaar-banking/aadhaar_logo.svg
  video_link: https://www.youtube.com/watch?time_continue=1&v=y-zLDNRPnBs&feature=emb_logo
  
  layout:
    - section: mid_summary
      small_description: Earn with Aadhaar Banking (AePS)
      header: Turn your shop into an ATM
    - section: single_hero
      title: Easy Cash Withdrawal
      text: AePS allows you to turn your shop into an ATM and lets your customers withdraw cash using their fingerprint.
      image: /images/aadhaar-banking/easy-cash-withdrawal.svg
    - section: short_ad
      title: Jan Dhan Government Benefit
      text: AePS allows your customers to withdraw their DBT (Direct Benefit Transfers) from government in their Jan Dhan account.
      image: /images/aadhaar-banking/jan_dhan.svg
    - section: alternating_steps
      steps:
      - title: Easy Cash Deposit
        text: AePS also allows you to turn your shop into a cash deposit machine. Your customers can then deposit cash at your shop with ease.
        image: /images/aadhaar-banking/easy-cash-deposit.svg
      - title: Quick Fund Transfer
        text: With AePS you will never have to go to a Bank or an ATM and you will not need a debit card also. Just transfer funds using your fingerprint.
        image: /images/aadhaar-banking/quick-fund-transfer.svg
      - title: Instant Balance-inquiry
        text: AePS allows your customers to check their bank balance at your shop instantly.
        image: /images/aadhaar-banking/instant-balance-inquiry.svg
      - title: Mini Statement
        text: AePS will also let your customers take the mini statement of their account at your shop
        image: /images/aadhaar-banking/mini-statement.svg
    - section: heros_main_section
      header: Benefits
      heros: 
        - type: pair
          # Benefit 1
          title_left: Earn Commission
          text_left: Earn commission for every cash-deposit, cash-withdrawal or balance-inquiry that your customer does at your shop. More transaction is more commission for you.
          image_left: /images/aadhaar-banking/earn-commission.svg
          # Benefit 2
          title_right: Best Success Rate
          text_right: Transaction failures occur rarely with our services. We ensure that you get the best success rate for every transaction. We are as reliable as banks themselves
          image_right: /images/aadhaar-banking/best-success-rate.svg
    - section: one_liner
      icon: /images/eko-trust.svg
      title: Eko's Trust
      text: You can assure your customers that their money and data is safe. Eko’s trust is unparalleled
    - section: step_section
      header: How to use Aadhaar Banking
      boxes:
      - title: 'Step 1:'
        text: Sign Up on Connect
        link: https://connect.eko.in/
      - title: 'Step 2:'
        text: Enable AePS using the Connect app
      - title: 'Step 3:'
        text: Register your biometric device
      - title: 'Step 4:'
        text: Start serving your customers
    - section: message
      line1: A customer who wishes to use your service would simply need to provide his aadhar number, name, and account number. 
      line2: The process to enable AePS and register your biometric device is easy.
      main_line: For all issues, we provide 24x7 support.
      button_text: Contact Support
    - section: small_heros_section
      header: Our Partners
      partner_images:
      - image: /images/aadhaar-banking/billdesk.png
      - image: /images/aadhaar-banking/nsdl.png
      - image: /images/aadhaar-banking/bharat.png
      - image: /images/aadhaar-banking/aeps.png
      - image: /images/aadhaar-banking/npcl.png
    - section: final_ad
      small_header: Ready to get started?
      main_header: Use Aadhaar Banking & Earn More
      image: /images/become-eko-partner.svg
      button1_text: Get Started
      button2_text: Contact Sales