backend:
  name: git-gateway
  branch: master
  # name: test-repo

local_backend: true

media_folder: "src/assets/img/blog"
public_folder: "/assets/img/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string", hint: "Title of the article that will show on top of the page"}
      - {label: "Description", name: "description", widget: "text", hint: "A short description of this article. Or, adding <!-- excerpt --> after the first paragraph will make that the description!"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "image", widget: "image"}
      - {label: "Business", name: "business", widget: "select", hint: "What business audience does this article target? Retailors or API Enterprise partners?", required: false, options: [ "api", "retail" ] }
      - {label: "Tags", name: "tags", widget: "list", hint: "Enter one or more tags associated with this article. Separate tags with comma. Ex: technology, finance", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "eloka-admin-announcement"
    label: "Eloka Admin Announcements"
    folder: "src/eloka-admin-announcement"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "admin_announcement"}
      - {label: "Title", name: "title", widget: "string", hint: "Title of the article that will show on top of the page"}
      - {label: "Description", name: "description", widget: "text", hint: "A short description of this article. Or, adding <!-- excerpt --> after the first paragraph will make that the description!"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "image", widget: "image"}
      - { label: "Eloka Use-Cases", name: "usecases", widget: "select", options: ["all"], multiple: true, default: ["all"] }
      - {label: "Body", name: "body", widget: "markdown"}
  # - name: "settings"
  #   label: "Settings"
  #   files:
  #     - name: "website settings"
  #       label: "Website Settings"
  #       file: "src/_data/website.yaml"
  #       fields:
  #         - {label: "Title", name: "title", widget: "string"}
  #         - {label: "Short Name", name: "short_name", widget: "string"}
  #         - {label: "Logo", name: "logo", widget: "image"}
  #         - {label: "Sign Up URL", name: "signup_url", widget: "string"}
  #         - {label: "Contact Us URL", name: "contact_url", widget: "string"}
  #         - {label: "Contact Email", name: "email", widget: "string"}
  #         - {label: "Company Description", name: "company_description", widget: "text"}
  #         - {label: "Keywords (SEO)", name: "keywords", widget: "string", hint: "These are keywords that are associated with this website that can help with website traffic and higher results in Google searches. (Separate keywords by commas) "}
  #         - {label: "Base Image", name: "image", widget: "image"}
  #         - {label: "Tag Line", name: "tag_line", widget: "string"}
  #         - {label: "Facebook Link", name: "facebook", widget: "string"}
  #         - {label: "LinkedIn Link", name: "linkedin", widget: "string"}
  #         - {label: "Twitter Link", name: "twitter", widget: "string"}
  #         - {label: "Twitter Handle", name: "twitter_handle", widget: "string"}
