backend:
  name: git-gateway
  branch: master
media_folder: "src/assets/img/blog"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Business", name: "business", widget: "select", required: false, options: [ {name: "API", value: "api"}, {name: "Retail", value: "retail"}, {name: "N/A", value: ""} ]}
      - {label: "Tags", name: "tags", widget: "list", hint: "Choose a theme or multiple themes associated with this blog post. Enter tags in a comma-separated list. Ex) technology, finance", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Settings"
    files:
      - name: "website settings"
        label: "Website Settings"
        file: "src/_data/website.yaml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Sign Up URL", name: "signup_url", widget: "string"}
          - {label: "Contact Us URL", name: "contact_url", widget: "string"}
          - {label: "Company Description", name: "company_description", widget: "text"}
          - {label: "Keywords (SEO)", name: "keywords", widget: "string", hint: "These are keywords that are associated with this website that can help with website traffic and higher results in Google searches. (Separate keywords by commas) "}
          - {label: "Base Image", name: "image", widget: "image"}
          - {label: "Tag Line", name: "tag_line", widget: "string"}
          - {label: "Facebook Link", name: "facebook", widget: "string"}
          - {label: "LinkedIn Link", name: "linkedin", widget: "string"}
          - {label: "Twitter Link", name: "twitter", widget: "string"}
          - {label: "Twitter Handle", name: "twitter_handle", widget: "string"}