backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
#publish_mode: editorial_workflow
media_folder: "src/images/blogs"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog_post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Tags", name: "tags", multiple: true, widget: "select",  options: ["technology", "finance"], hint: "Choose a theme associated with this blog post.", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "settings" 
    label: "Settings"
    files: 
      - name: "website settings"
        label: "Website Settings"
        file: "src/_data/website.yaml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Base URL", name: "base_url", widget: "string"}
          - {label: "Sign Up URL", name: "signup_url", widget: "string"}
          - {label: "Contact Us URL", name: "contact_url", widget: "string"}
          - {label: "Company Description", name: "company_description", widget: "text"}
          - {label: "Keywords (SEO)", name: "keywords", widget: "string", hint: "These are keywords that are associated with this website that can help with website traffic and higher results in Google searches. (Separate keywords by commas) "}
          - {label: "Base Image", name: "image", widget: "image"}
          - {label: "Tag Line", name: "tag_line", widget: "string"}
          - {label: "Facebook Link", name: "facebook", widget: "string"}
          - {label: "LinkedIn Link", name: "linkedin", widget: "string"}
          - {label: "Twitter Link", name: "twitter", widget: "string"}
          - {label: "Twitter Handle", name: "twitter_handle", widget: "string"}